name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4

    - name: Start MySQL Service
      run: sudo systemctl start mysql.service

    - name: Create MySQL Database
      run: mysql -uroot -h127.0.0.1 -proot -e 'CREATE DATABASE IF NOT EXISTS drupal;'

    - name: Composer Install Drupal codebase
      run: |
        composer create-project --no-progress drupal/recommended-project:^8.9 .

    - name: Install Drupal
      run: |
        composer require --no-progress drush/drush
        vendor/bin/drush si --db-url=mysql://root:root@localhost:3306/drupal -y

    - name: Checkout Swagger UI Formatter
      uses: actions/checkout@v2
      with:
        path: ./web/modules/custom/swagger_ui_formatter

    - name: Install Swagger UI Formatter development dependencies
      run: |
        cd ./web/modules/custom/swagger_ui_formatter
        composer install --no-progress
