name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Composer Install Drupal codebase
      run: |
        'composer create-project --no-progress drupal/recommended-project .'
        'ls -al'
      
    - name: Checkout Wodby containers
      uses: actions/checkout@v2
      with:
        repository: wodby/docker4drupal
        ref: 5.4.24
#        path: .

    - name: Start up Wodby containers
      run: |
        ls -al
        rm docker-compose.override.yml
        docker-compose up --build -d

    - name: Install Drupal
      run: 'docker-compose exec -T php bash -c "composer require drush/drush && drush si --db-url=mysql://drupal:drupal@mariadb:3306/drupal -y"'
