name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Composer Install Drupal codebase
      run: 'composer create-project --no-progress drupal/recommended-project .'
      
    - name: Checkout Wodby containers
      uses: actions/checkout@v2
      with:
        repository: wodby/docker4drupal
        ref: 5.4.24
#        path: .

    - name: Remove docker-compose.override.yml
      run: rm docker-compose.override.yml
      
    - name: Start up Wodby containers 
      run: 'docker-compose up --build -d'

    
    - name: Install Drupal
      run: |
        'composer require --no-progress drush/drush'
        'drush si --db-url=mysql://drupal:drupal@mariadb:3306/drupal -y'
#        'docker-compose exec -T php bash -c "composer require drush/drush"'  # why is this failing?

#     - name: Checkout Swagger UI Formatter
#       uses: actions/checkout@v2
#       with:
#         path: ./web/modules/custom

#     - name: Install Swagger UI Formatter
#       run: |
#         'cd web/modules/custom/swagger_ui_formatter'
#         'composer install'
#         'docker-compose exec -T php bash -c "drush en swagger_ui_formatter -y"'




#     - name: Install dependencies
#       if: steps.composer-cache.outputs.cache-hit != 'true'
#       run: composer install --prefer-dist --no-progress --no-suggest

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
