name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Composer Install Drupal codebase
      run: |
        composer create-project --no-progress drupal/recommended-project .
      
    - name: Checkout Wodby containers
      uses: actions/checkout@v2
      with:
        repository: wodby/docker4drupal
        ref: 5.4.24
        path: ./tools/wodby

    - name: Start up Wodby containers
      run: |
        cp ./tools/wodby/docker-compose.yml ./tools/wodby/.env .
        docker-compose up --build -d

    - name: Install Drupal
      run: |
        composer require --no-progress drush/drush
        cp ./web/sites/default/default.settings.php ./web/sites/default/settings.php
        chmod a+w ./web/sites/default/settings.php
        docker-compose exec -T php bash -c "drush si --db-url=mysql://drupal:drupal@mariadb:3306/drupal -y"
